name: minify

on:
  push:
    branches:
      - 'main'

jobs:
  minify:
    runs-on: ubuntu-latest
    steps:
      # Installing tools
      - uses: actions/checkout@v6.0.2
      - run:
          npm install -g minify;
          sudo apt update;
          sudo apt install -y moreutils
      
      # Finding the files and minifying it
      - run: >
          find -P * \( -iname '*.html' -o -iname '*.css' -o -iname '*.js' \) -exec bash -c 'minify $1 | sponge $1' sh {} \; ;
          find -P * -iname '*.json' -exec bash -c 'jq . -c $1 | sponge $1' sh {} \;
      
      # Removing junk files
      - run: >
          rm README.md;
          find . -mindepth 1 -name '.*' -prune -exec rm -rf {} \;
      
      # Displaying files
      - run: >
          echo 'Available Files:';
          find -P * -type f -exec echo -e ' > {}\n' \; -exec bash -c '( ! [[ $1 =~ .(png|woff) ]] && cat $1 && echo )' sh {} \;
      
      # Pushing the changes to `gh-pages` branch
      - run: |
          git config user.name MacStevins
          git config user.email minifier@macstevins.github.com
          git add .
          git commit -am 'Automated minify of ${{ github.sha }}'
          git push --force -u origin main:gh-pages